twig:
    file_name_pattern: '*.twig'

    form_themes:
        - '@EasyAdmin/crud/form_theme.html.twig'
        
    globals:
        # Use a different admin layout instead of the default "@EasyAdmin/layout.html.twig"
        # theme_layout: "_sample"
        # This will use "bundles/Themes/_sample/layout.html.twig"
        theme_layout: ''

when@test:
    twig:
        strict_variables: true
