vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       media:
           uri_prefix: /media
           upload_destination: '%kernel.project_dir%/public/media'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
           directory_namer:
                service: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
                options:
                    date_time_format: 'M-Y'
                    date_time_property: updatedAt
