# This YAML file contains custom application configuration settings, with placeholders for dynamic substitution:

# - %env()% for environmental variables from .env
# - %self()% for values within this file
# - %params% for Symfony parameters from services.yaml.

# Warning: Avoid circular references when using %self()% placeholders to prevent recursion. For Example:

# app.name: '%self(app.title)%'
# app.title: '%self(app.name)%' -> This will cause a recursion

app:

  name: 'User Synthetics'

  # if not using cdn or external link, logo must reside inside public/ directory
  logo: '/resource/images/system/golden-logo-template-free-png.webp'

  slogan: 'Empower Your Admin Experience with %self(app.name)%'

  description: >
    Introducing %self(app.name)%, your ultimate companion for effortlessly crafting sleek and powerful admin dashboards! 
    With %self(app.name)%, developers can bid farewell to tedious coding and welcome a seamless, intuitive framework 
    designed to streamline the entire dashboard development process

# Administrative Contact Information
# This section provides essential details for administrative inquiries and correspondence.

contact:

  email: 'sample@email.com'

  phone: '+2234904994'

  address: >
    123 Main Street
    Anytown, CA 12345 
    United States

# User-related configurations
# This section encompasses settings pertinent to user-related functionalities.

user:

  email:

    # Whether to send an email validation link upon registration.
    send_validation_link: false

    # If true, users cannot change their email address.
    prevent_update: true
    
    # If true, users must reconfirm their email after any change.
    reconfirm_on_update: true
  
  account:

    # Users must verify their email before they can log in.
    login_only_if_verified: true

    # If true, accounts inactive for a specified duration will be deleted.
    delete_if_inactive: true

    # Number of days after registration when an inactive account will be deleted.
    # > This option will not take effect if "delete_if_inactive" is set to false
    inactive_account_expiration_days: 7

# Custom Configurations
# You can add and manager your own custom configuration and access them easily via the ConfigurationService provided by Easyadmin Ultimate
