# This YAML file contains custom configuration settings for the application.
# Values enclosed within %env()% or %param% placeholders can be dynamically 
# substituted with environment variables or parameters defined elsewhere in 
# the Symfony application.

# Example:
#   env_value: '%env(MY_ENV_VAR)%'
#   param_value: '%param(my_parameter)%'

app:

  title: 'zap %env(APP_ENV)%'

  name: 'User Synthetics %self(app.title)%'

  logo: '/resource/images/system/golden-logo-template-free-png.webp'

  slogan: 'Empower Your Admin Experience with %self(app.name)%'

  description: >
    Introducing User Synthetics, your ultimate companion for effortlessly crafting sleek and powerful admin dashboards! 
    With User Synthetics, developers can bid farewell to tedious coding and welcome a seamless, intuitive framework 
    designed to streamline the entire dashboard development process

###> Administrative contact information

office:

  # Primary email address for administrative contact.
  email: 'sample@email.com'

  # Contact phone number.
  phone: '+2234904994'

  address: >
    123 Main Street
    Anytown, CA 12345 
    United States

###> User-related configurations

user:

  email:

    # Whether to send an email validation link upon registration.
    send_validation_link: true

    # If true, users cannot change their email address.
    prevent_update: true
    
    # If true, users must reconfirm their email after any change.
    reconfirm_on_update: true
  
  account:

    # Users must verify their email before they can log in.
    login_only_if_verified: true

    # If true, accounts inactive for a specified duration will be deleted.
    delete_if_inactive: true

    # Number of days after registration when an inactive account will be deleted.
    # > This option will not take effect if "delete_if_inactive" is set to false
    inactive_account_expiration_days: 7
